### ISSUE TITLE
Use WebCryptoAPI when available

### ISSUE THREAD

**Issue by diafygi** [arlolra/otr#62]
Since WebCrypto API is starting to show up in browsers, I'd like to request that it be used instead of CryptoJS when available (similar to the way OpenPGP.js is doing it[[1]](https://github.com/openpgpjs/openpgpjs/issues/91)).

**Comment by diafygi** [comment]
FYI, this can be closed if you want. I just wanted to see if there would be any interest in a pull request that adds this feature.

**Comment by arlolra** [comment]
Pull requests welcome!

You may be interested in tuning in to the larger refactoring discussion in #59.
