### ISSUE TITLE
OMEMO.js

### ISSUE THREAD

**Issue by GreenLunar** [arlolra/otr#76]
Is there any chance for you to join to @omemo and experiment with OMEMO.js?

It would be quite a challenge, since OMEMO is Device Trusted.

> With OMEMO you no longer trust user identities but device identities. If you are communicating with a contact for the first time or if that contact recently got a new device, you will be presented with a fingerprint for that device. You can then either verify that fingerprint out of band (for example via a quick phone call) or, if you are reasonably sure that your transport is secure (for instance if you are chatting on the same, trusted server), you can choose to trust a device on first use. If you have trusted devices of your contact in the past you can also use those devices as a secure channel to verify the fingerprint of a new device by having your contact verify the fingerprint via chat.

Read more at https://conversations.im/omemo/

**Comment by arlolra** [comment]
v3 of the OTR spec already has the idea of device identities. I don't think in the OMEMO case it has anything to do with native APIs on mobile devices, if that's what you were thinking was a challenge for JavaScript. It probably just means not having to sync your private keys to each device, and instead generating one per device.

OMEMO is based on the Axolotl protocol, of which there are already several JS implementations,
https://github.com/WhisperSystems/Signal-Desktop/blob/master/libtextsecure/libaxolotl.js
https://github.com/joebandenburg/libaxolotl-javascript

But, to answer your question, and as for the rest of the PEPs, it's probably something I'll look into for Tor Messenger down the road. Thanks.
https://trac.torproject.org/projects/tor/ticket/17457

**Comment by GreenLunar** [comment]
Thank you for your elaborated answer.

**Comment by GreenLunar** [comment]
Apparently, [Cryptocat](https://github.com/cryptocat/cryptocat) is utilizing an OMEMO.js module.

**Comment by arlolra** [comment]
Yup, there's a new Cryptocat v3 in town.
